/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions.
// Keep it committed so TypeScript understands Next.js types immediately.
