"use client";

import React from "react";

import { buildCustomRuleset, mergeRulesetDraft, rulesetToCustomInput, type CustomRulesetInput, type RulesetOverrides } from "@/engine/rulesets/custom";
import { CONTREE_KFFR_RULESET } from "@/engine/rulesets/presets";
import { RulesetSummary } from "./RulesetSummary";

type Props = { value: CustomRulesetInput; onChange: (value: CustomRulesetInput) => void; disabled?: boolean };

function Toggle({ label, description, checked, disabled, why, onChange }: { label: string; description: string; checked: boolean; disabled?: boolean; why?: string; onChange: (checked: boolean) => void }) {
  return <label className={`flex gap-3 rounded-md p-2 ${disabled ? "bg-stone-100 text-stone-400" : "hover:bg-stone-50"}`} title={disabled ? why : undefined}>
    <input className="mt-1 size-4 shrink-0" type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} />
    <span><span className="block font-semibold">{label}</span><span className="block text-xs opacity-75">{disabled && why ? why : description}</span></span>
  </label>;
}

export function RulesetConfigurator({ value, onChange, disabled = false }: Props) {
  const rules = buildCustomRuleset(value);
  const update = (patch: RulesetOverrides) => onChange(mergeRulesetDraft(value, patch));
  const toggle = (section: keyof RulesetOverrides, key: string, checked: boolean) => update({ [section]: { [key]: checked } } as RulesetOverrides);
  const announcementsDisabled = disabled || !rules.announcements.enabled;
  const coincheDisabled = disabled || !rules.bidding.allowCoinche;
  const beloteDisabled = disabled || !rules.belote.enabled;
  return <div className="max-h-[80dvh] space-y-3 overflow-y-auto overflow-x-hidden p-1 text-sm">
    <div className="sticky top-0 z-10 rounded-lg border bg-white p-3 shadow-sm">
      <label className="font-semibold">Variante<select className="ml-3 rounded border px-2 py-1" disabled={disabled} value={rules.id === "contree-kffr" ? "contree-kffr" : "custom"} onChange={(event) => event.target.value === "contree-kffr" && onChange({ presetId: "contree-kffr" })}><option value="contree-kffr">Contrée KFFR</option><option value="custom">Personnalisée</option></select></label>
      <button className="ml-3 rounded border px-2 py-1 font-semibold disabled:opacity-50" type="button" disabled={disabled} onClick={() => onChange(rulesetToCustomInput(CONTREE_KFFR_RULESET))}>Réinitialiser aux règles Contrée KFFR</button>
    </div>
    <RulesetSummary ruleset={rules} compact />
    <details open className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Partie</summary><div className="mt-3"><label className="font-semibold">Score cible<select className="ml-3 rounded border px-2 py-1" disabled={disabled} value={[500,1000,1500,2000].includes(rules.game.targetScore) ? rules.game.targetScore : "custom"} onChange={(e) => e.target.value !== "custom" && update({ game: { targetScore: Number(e.target.value) } })}>{[500,1000,1500,2000].map((score) => <option key={score}>{score}</option>)}<option value="custom">Personnalisé</option></select></label><input aria-label="Score cible personnalisé" className="ml-2 w-28 rounded border px-2 py-1" disabled={disabled} min={100} max={100000} type="number" value={rules.game.targetScore} onChange={(e) => { const score = Number(e.target.value); if (score >= 100 && score <= 100000) update({ game: { targetScore: score } }); }} /></div></details>
    <details open className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Contrats</summary><div className="mt-2 grid gap-1 sm:grid-cols-2">
      <Toggle label="Capot" description="Permet d'annoncer les huit plis." checked={rules.bidding.allowCapot} disabled={disabled} onChange={(v) => toggle("bidding","allowCapot",v)} />
      <Toggle label="Coinche" description="La défense peut contrer le contrat." checked={rules.bidding.allowCoinche} disabled={disabled} onChange={(v) => toggle("bidding","allowCoinche",v)} />
      <Toggle label="Surcoinche" description="Le camp preneur peut répondre à la Coinche." checked={rules.bidding.allowSurcoinche} disabled={coincheDisabled} why="Activez d'abord la Coinche." onChange={(v) => toggle("bidding","allowSurcoinche",v)} />
      <Toggle label="Sans Atout" description="Ordre et points hors-atout dans les quatre couleurs." checked={rules.bidding.allowNoTrump} disabled={disabled} onChange={(v) => toggle("bidding","allowNoTrump",v)} />
      <Toggle label="Tout Atout" description="Ordre et points d'atout dans les quatre couleurs." checked={rules.bidding.allowAllTrump} disabled={disabled} onChange={(v) => toggle("bidding","allowAllTrump",v)} />
    </div></details>
    <details className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Annonces</summary><Toggle label="Jouer avec les annonces" description="Active les combinaisons annoncées." checked={rules.announcements.enabled} disabled={disabled} onChange={(v) => toggle("announcements","enabled",v)} /><div className="grid sm:grid-cols-2"><Toggle label="Tierce" description="3 cartes consécutives." checked={rules.announcements.tierce} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("announcements","tierce",v)} /><Toggle label="Cinquante" description="4 cartes consécutives." checked={rules.announcements.fifty} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("announcements","fifty",v)} /><Toggle label="Cent" description="5 cartes consécutives ou plus." checked={rules.announcements.hundred} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("announcements","hundred",v)} /><Toggle label="Carrés" description="4 cartes de même hauteur selon le barème." checked={rules.announcements.squares} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("announcements","squares",v)} /></div></details>
    <details className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Belote</summary><Toggle label="Belote / Rebelote" description="Roi et Dame d'atout." checked={rules.belote.enabled} disabled={disabled} onChange={(v) => toggle("belote","enabled",v)} /><label className="block p-2 font-semibold">Valeur <input className="ml-2 w-20 rounded border px-2 py-1" type="number" min={0} disabled={beloteDisabled} value={rules.belote.points} onChange={(e) => update({ belote: { points: Number(e.target.value) } })} /></label><Toggle label="Compte pour réussir le contrat" description="Ajoute la Belote aux points du preneur." checked={rules.belote.countsForContractSuccess} disabled={beloteDisabled} why="Activez la Belote." onChange={(v) => toggle("belote","countsForContractSuccess",v)} /><Toggle label="Compte pour faire chuter le contrat" description="Ajoute la Belote aux points de la défense." checked={rules.belote.countsForContractFailure} disabled={beloteDisabled} why="Activez la Belote." onChange={(v) => toggle("belote","countsForContractFailure",v)} /><Toggle label="Belote/Rebelote en Tout Atout" description="Chaque couleur peut produire une Belote." checked={rules.belote.allowInAllTrump} disabled={beloteDisabled || !rules.bidding.allowAllTrump} why="Activez la Belote et Tout Atout." onChange={(v) => toggle("belote","allowInAllTrump",v)} /></details>
    <details className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Jeu de la carte</summary>{[["mustFollowSuit","Obligation de fournir","Jouer la couleur demandée si possible."],["mustTrumpWhenVoid","Obligation de couper","Couper lorsqu'on n'a pas la couleur demandée."],["mustOvertrump","Obligation de surcouper","Monter sur l'atout adverse si possible."],["mustRaiseAtTrump","Obligation de monter à l'atout","Monter lorsque l'atout est demandé."],["allowDiscardWhenPartnerWinning","Défausse autorisée si le partenaire est maître","Permet de ne pas couper derrière son partenaire."],["allowDiscardWhenCannotOvertrump","Défausse autorisée si je ne peux pas surcouper","Permet de jeter une autre couleur."]] .map(([key,label,description]) => <Toggle key={key} label={label} description={description} checked={rules.cardPlay[key as keyof typeof rules.cardPlay]} disabled={disabled} onChange={(v) => toggle("cardPlay",key,v)} />)}</details>
    <details className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Réussite du contrat</summary><Toggle label="Le preneur doit atteindre son contrat" description="Ses points doivent atteindre la valeur annoncée." checked={rules.contractSuccess.mustReachBid} disabled={disabled} onChange={(v) => toggle("contractSuccess","mustReachBid",v)} /><Toggle label="Le preneur doit battre la défense" description="Une égalité ne suffit pas." checked={rules.contractSuccess.mustBeatDefense} disabled={disabled} onChange={(v) => toggle("contractSuccess","mustBeatDefense",v)} /><Toggle label="Les annonces comptent pour réussir le contrat" description="Exemple : 88 aux plis + tierce = 108." checked={rules.contractSuccess.announcementsCount} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("contractSuccess","announcementsCount",v)} /></details>
    <details className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Comptage des points</summary><label className="block p-2 font-semibold">Mode de score<select className="ml-2 rounded border px-2 py-1" disabled={disabled} value={rules.scoring.mode} onChange={(e) => update({ scoring: { mode: e.target.value as typeof rules.scoring.mode } })}><option value="ffb">FFB</option><option value="contract-only">Contrat uniquement</option><option value="contract-only-160-failure">Contrat uniquement / base de chute</option><option value="points-only">Points réalisés</option></select></label><Toggle label="Arrondir à la dizaine" description="Arrondi réglementaire en fin de manche." checked={rules.scoring.roundToTen} disabled={disabled} onChange={(v) => toggle("scoring","roundToTen",v)} /><Toggle label="Doubler tous les points en cas de Coinche" description="Applique le coefficient au score complet." checked={rules.scoring.doubleAllPointsOnCoinche} disabled={coincheDisabled} why="Activez la Coinche." onChange={(v) => toggle("scoring","doubleAllPointsOnCoinche",v)} /><Toggle label="Transférer les annonces en cas de chute" description="La défense récupère les annonces du preneur." checked={rules.scoring.announcementsLostOnFailure} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("scoring","announcementsLostOnFailure",v)} /><Toggle label="Transférer les annonces en cas de capot" description="Le camp du capot récupère les annonces." checked={rules.scoring.announcementsLostOnCapot} disabled={announcementsDisabled} why="Activez les annonces." onChange={(v) => toggle("scoring","announcementsLostOnCapot",v)} /></details>
    <details className="rounded-lg border bg-white p-3"><summary className="cursor-pointer font-bold">Options avancées</summary>{[["coincheMultiplier","Multiplicateur Coinche"],["surcoincheMultiplier","Multiplicateur Surcoinche"]].map(([key,label]) => <label key={key} className="block p-2 font-semibold">{label}<input className="ml-2 w-20 rounded border px-2 py-1" type="number" min={1} disabled={coincheDisabled} value={rules.scoring[key as "coincheMultiplier"|"surcoincheMultiplier"]} onChange={(e) => update({ scoring: { [key]: Number(e.target.value) } })} /></label>)}</details>
  </div>;
}
