"use client";
/* eslint-disable react/no-unescaped-entities -- French dependency explanations use apostrophes. */

import React, { useEffect, useState } from "react";

import { buildCustomRuleset, mergeRulesetDraft, rulesetToCustomInput, type CustomRulesetInput, type RulesetOverrides } from "@/engine/rulesets/custom";
import { CONTREE_KFFR_RULESET } from "@/engine/rulesets/presets";

const RULE_SECTIONS = [
  ["game", "Partie"], ["contracts", "Contrats"], ["announcements", "Annonces"], ["belote", "Belote"],
  ["card-play", "Jeu"], ["success", "Réussite du contrat"], ["score", "Score"], ["advanced", "Avancé"],
] as const;
type RuleSection = typeof RULE_SECTIONS[number][0];

const MIN_TARGET_SCORE = 100;
const MAX_TARGET_SCORE = 100_000;
const TARGET_SCORE_STEP = 500;

export function parseTargetScoreInput(input: string) {
  if (!input.trim()) return null;
  const score = Number(input);
  return Number.isFinite(score) && score >= MIN_TARGET_SCORE && score <= MAX_TARGET_SCORE
    ? score
    : null;
}

type Props = { value: CustomRulesetInput; onChange: (value: CustomRulesetInput) => void; disabled?: boolean };

function Toggle({ label, description, checked, disabled, why, onChange }: { label: string; description: string; checked: boolean; disabled?: boolean; why?: string; onChange: (checked: boolean) => void }) {
  return <label className={`group flex items-start justify-between gap-4 rounded-xl border p-3 transition ${disabled ? "border-white/[0.05] bg-white/[0.025] text-white/35" : "border-white/[0.08] bg-white/[0.045] text-white hover:border-emerald-300/25 hover:bg-white/[0.07]"}`} title={disabled ? why : undefined}>
    <span><span className="block font-bold">{label}</span><span className="mt-0.5 block text-xs leading-relaxed opacity-60">{disabled && why ? why : description}</span></span>
    <span className="relative mt-0.5 shrink-0"><input className="peer absolute inset-0 z-10 h-full w-full cursor-pointer opacity-0" type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span aria-hidden="true" className="pointer-events-none block h-6 w-11 rounded-full bg-white/15 shadow-inner transition peer-checked:bg-emerald-600 peer-focus-visible:outline peer-focus-visible:outline-3 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-emerald-300 peer-disabled:opacity-40 after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow after:transition-transform after:content-[''] peer-checked:after:translate-x-5" /></span>
  </label>;
}

export function RulesetConfigurator({ value, onChange, disabled = false }: Props) {
  const [active, setActive] = useState<RuleSection>("game");
  const [confirmReset, setConfirmReset] = useState(false);
  const rules = buildCustomRuleset(value);
  const [targetScoreInput, setTargetScoreInput] = useState(() => String(rules.game.targetScore));
  const update = (patch: RulesetOverrides) => onChange(mergeRulesetDraft(value, patch));
  const toggle = (section: keyof RulesetOverrides, key: string, checked: boolean) => update({ [section]: { [key]: checked } } as RulesetOverrides);
  const announcementsDisabled = disabled || !rules.announcements.enabled;
  const coincheDisabled = disabled || !rules.bidding.allowCoinche;
  const beloteDisabled = disabled || !rules.belote.enabled;
  const resetRules = () => { onChange(rulesetToCustomInput(CONTREE_KFFR_RULESET)); setConfirmReset(false); };
  const sectionClass = "rounded-2xl border border-white/[0.08] bg-white/[0.04] p-3.5 text-white shadow-inner sm:p-4";
  useEffect(() => setTargetScoreInput(String(rules.game.targetScore)), [rules.game.targetScore]);
  const applyTargetScore = (input: string) => {
    const score = parseTargetScoreInput(input);
    if (score === null) {
      setTargetScoreInput(String(rules.game.targetScore));
      return;
    }
    setTargetScoreInput(String(score));
    if (score !== rules.game.targetScore) update({ game: { targetScore: score } });
  };
  const stepTargetScore = (direction: 1 | -1) => {
    const current = parseTargetScoreInput(targetScoreInput) ?? rules.game.targetScore;
    const score = Math.min(MAX_TARGET_SCORE, Math.max(MIN_TARGET_SCORE, current + direction * TARGET_SCORE_STEP));
    setTargetScoreInput(String(score));
    if (score !== rules.game.targetScore) update({ game: { targetScore: score } });
  };
  return <div className="coinche-rules-configurator flex h-full min-h-0 flex-col bg-[#091711] text-sm text-stone-100">
    <div className="shrink-0 border-b border-white/10 bg-[#102219] p-3 sm:p-4"><div className="flex flex-wrap items-center gap-2"><label className="font-bold text-white/75">Variante <select className="ml-2 px-3 py-1.5" disabled={disabled} value={rules.id === "contree-kffr" ? "contree-kffr" : "custom"} onChange={(event) => event.target.value === "contree-kffr" && (rules.id === "custom" ? setConfirmReset(true) : resetRules())}><option value="contree-kffr">Contrée KFFR</option><option value="custom">Personnalisée</option></select></label><button className="rounded-xl border border-red-300/15 bg-red-950/25 px-3 py-2 font-bold text-red-100 disabled:opacity-50" type="button" disabled={disabled} onClick={() => rules.id === "custom" ? setConfirmReset(true) : resetRules()}>Réinitialiser</button>{confirmReset ? <span className="flex items-center gap-1 rounded-xl border border-red-300/15 bg-red-950/30 p-1"><span className="px-1 text-xs">Confirmer ?</span><button className="rounded-lg bg-red-700 px-2 py-1 font-bold text-white" onClick={resetRules} type="button">Oui</button><button className="rounded-lg border border-white/10 bg-white/5 px-2 py-1" onClick={() => setConfirmReset(false)} type="button">Non</button></span> : null}</div></div>
    <div className="flex min-h-0 flex-1 flex-col md:grid md:grid-cols-[210px_minmax(0,1fr)]"><nav aria-label="Sections des règles" className="flex shrink-0 gap-1 overflow-x-auto border-b border-white/10 bg-[#0c1c15] p-2 md:flex-col md:overflow-visible md:border-b-0 md:border-r md:p-4">{RULE_SECTIONS.map(([id,label]) => <button aria-current={active === id ? "page" : undefined} className={`whitespace-nowrap rounded-xl border px-3 py-2.5 text-left font-bold transition ${active === id ? "border-[#ead8a6]/30 bg-[#ead8a6] text-[#10251b] shadow" : "border-transparent bg-transparent text-white/55 hover:border-white/10 hover:bg-white/[0.06] hover:text-white"}`} key={id} onClick={() => setActive(id)} type="button">{label}</button>)}</nav><div className="min-h-0 flex-1 overflow-y-auto bg-[radial-gradient(circle_at_top_right,rgb(31_101_69_/_16%),transparent_45%)] p-3 sm:p-5">
    <section aria-labelledby="rules-game" hidden={active !== "game"} className={sectionClass}><h3 className="font-bold" id="rules-game">Partie</h3><div className="mt-3 flex flex-wrap gap-2"><label className="font-semibold">Score cible<select className="ml-3 rounded border px-2 py-1" disabled={disabled} value={[500,1000,1500,2000].includes(rules.game.targetScore) ? rules.game.targetScore : "custom"} onChange={(e) => e.target.value !== "custom" && update({ game: { targetScore: Number(e.target.value) } })}>{[500,1000,1500,2000].map((score) => <option key={score}>{score}</option>)}<option value="custom">Personnalisé</option></select></label><input aria-label="Score cible personnalisé" className="w-28 rounded border px-2 py-1" disabled={disabled} max={MAX_TARGET_SCORE} step={TARGET_SCORE_STEP} type="number" value={targetScoreInput} onBlur={(event) => applyTargetScore(event.currentTarget.value)} onChange={(event) => { const input = event.target.value; setTargetScoreInput(input); const score = parseTargetScoreInput(input); if (score !== null && score !== rules.game.targetScore) update({ game: { targetScore: score } }); }} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); applyTargetScore(event.currentTarget.value); event.currentTarget.blur(); } else if (event.key === "ArrowUp" || event.key === "ArrowDown") { event.preventDefault(); stepTargetScore(event.key === "ArrowUp" ? 1 : -1); } }} /></div></section>
    <section aria-labelledby="rules-contracts" hidden={active !== "contracts"} className={sectionClass}><h3 className="font-bold" id="rules-contracts">Contrats</h3><div className="mt-2 grid gap-1 sm:grid-cols-2">
      <Toggle label="Capot" description="Permet d'annoncer les huit plis." checked={rules.bidding.allowCapot} disabled={disabled} onChange={(v) => toggle("bidding","allowCapot",v)} />
      <Toggle label="Générale" description="Un joueur s'engage à remporter seul les 8 plis. Son partenaire ne joue pas la donne." checked={rules.bidding.allowGenerale} disabled={disabled} onChange={(v) => toggle("bidding","allowGenerale",v)} />
      <Toggle label="Coinche" description="La défense peut contrer le contrat." checked={rules.bidding.allowCoinche} disabled={disabled} onChange={(v) => toggle("bidding","allowCoinche",v)} />
      <Toggle label="Surcoinche" description="Le camp preneur peut répondre à la Coinche." checked={rules.bidding.allowSurcoinche} disabled={coincheDisabled} why="Activez d'abord la Coinche." onChange={(v) => toggle("bidding","allowSurcoinche",v)} />
      <Toggle label="Sans Atout" description="Ordre et points hors-atout dans les quatre couleurs." checked={rules.bidding.allowNoTrump} disabled={disabled} onChange={(v) => toggle("bidding","allowNoTrump",v)} />
      <Toggle label="Tout Atout" description="Ordre et points d'atout dans les quatre couleurs." checked={rules.bidding.allowAllTrump} disabled={disabled} onChange={(v) => toggle("bidding","allowAllTrump",v)} />
    </div></section>
    <section aria-labelledby="rules-announcements" hidden={active !== "announcements"} className={sectionClass}><h3 className="font-bold" id="rules-announcements">Annonces</h3><Toggle label="Jouer avec les annonces" description="Active les combinaisons annoncées." checked={rules.announcements.enabled} disabled={disabled} onChange={(v) => toggle("announcements","enabled",v)} /><div className="grid sm:grid-cols-2"><Toggle label="Tierce" description="3 cartes consécutives." checked={rules.announcements.tierce} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","tierce",v)} /><Toggle label="Cinquante" description="4 cartes consécutives." checked={rules.announcements.fifty} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","fifty",v)} /><Toggle label="Cent" description="5 cartes consécutives ou plus." checked={rules.announcements.hundred} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","hundred",v)} /><Toggle label="Carrés" description="4 cartes de même hauteur selon le barème." checked={rules.announcements.squares} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","squares",v)} /></div></section>
    <section aria-labelledby="rules-belote" hidden={active !== "belote"} className={sectionClass}><h3 className="font-bold" id="rules-belote">Belote</h3><Toggle label="Belote / Rebelote" description="Roi et Dame d'atout." checked={rules.belote.enabled} disabled={disabled} onChange={(v) => toggle("belote","enabled",v)} /><label className="block p-2 font-semibold">Valeur <input className="ml-2 w-20 rounded border px-2 py-1" type="number" min={0} disabled={beloteDisabled} value={rules.belote.points} onChange={(e) => update({ belote: { points: Number(e.target.value) } })} /></label>{beloteDisabled ? <p className="px-2 text-xs text-stone-500">Activez d'abord la Belote / Rebelote.</p> : null}<Toggle label="Compte pour réussir le contrat" description="Ajoute la Belote aux points du preneur." checked={rules.belote.countsForContractSuccess} disabled={beloteDisabled} why="Activez d'abord la Belote." onChange={(v) => toggle("belote","countsForContractSuccess",v)} /><Toggle label="Compte pour faire chuter le contrat" description="Ajoute la Belote aux points de la défense." checked={rules.belote.countsForContractFailure} disabled={beloteDisabled} why="Activez d'abord la Belote." onChange={(v) => toggle("belote","countsForContractFailure",v)} /><Toggle label="Belote/Rebelote en Tout Atout" description="Chaque couleur peut produire une Belote." checked={rules.belote.allowInAllTrump} disabled={beloteDisabled || !rules.bidding.allowAllTrump} why="Activez d'abord Tout Atout et Belote / Rebelote." onChange={(v) => toggle("belote","allowInAllTrump",v)} /></section>
    <section aria-labelledby="rules-card-play" hidden={active !== "card-play"} className={sectionClass}><h3 className="font-bold" id="rules-card-play">Jeu</h3>{[["mustFollowSuit","Obligation de fournir","Jouer la couleur demandée si possible."],["mustTrumpWhenVoid","Obligation de couper","Couper lorsqu'on n'a pas la couleur demandée."],["mustOvertrump","Obligation de surcouper","Monter sur l'atout adverse si possible."],["mustRaiseAtTrump","Obligation de monter à l'atout","Monter lorsque l'atout est demandé."],["allowDiscardWhenPartnerWinning","Défausse autorisée si le partenaire est maître","Permet de ne pas couper derrière son partenaire."],["allowDiscardWhenCannotOvertrump","Défausse autorisée si je ne peux pas surcouper","Permet de jeter une autre couleur."]] .map(([key,label,description]) => <Toggle key={key} label={label} description={description} checked={rules.cardPlay[key as keyof typeof rules.cardPlay]} disabled={disabled} onChange={(v) => toggle("cardPlay",key,v)} />)}</section>
    <section aria-labelledby="rules-success" hidden={active !== "success"} className={sectionClass}><h3 className="font-bold" id="rules-success">Réussite du contrat</h3><Toggle label="Le preneur doit atteindre son contrat" description="Ses points doivent atteindre la valeur annoncée." checked={rules.contractSuccess.mustReachBid} disabled={disabled} onChange={(v) => toggle("contractSuccess","mustReachBid",v)} /><Toggle label="Le preneur doit battre la défense" description="Une égalité ne suffit pas." checked={rules.contractSuccess.mustBeatDefense} disabled={disabled} onChange={(v) => toggle("contractSuccess","mustBeatDefense",v)} /><Toggle label="Les annonces comptent pour réussir le contrat" description="Exemple : 88 aux plis + tierce = 108." checked={rules.contractSuccess.announcementsCount} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("contractSuccess","announcementsCount",v)} /></section>
    <section aria-labelledby="rules-score" hidden={active !== "score"} className={sectionClass}><h3 className="font-bold" id="rules-score">Score</h3><label className="block p-2 font-semibold">Mode de score<select className="ml-2 rounded border px-2 py-1" disabled={disabled} value={rules.scoring.mode} onChange={(e) => update({ scoring: { mode: e.target.value as typeof rules.scoring.mode } })}><option value="ffb">Officiel</option><option value="contract-only">Contrat uniquement</option><option value="contract-only-160-failure">Contrat uniquement / base de chute</option><option value="points-only">Points réalisés</option></select></label><Toggle label="Arrondir à la dizaine" description="Arrondi réglementaire en fin de manche." checked={rules.scoring.roundToTen} disabled={disabled} onChange={(v) => toggle("scoring","roundToTen",v)} /><Toggle label="Doubler tous les points en cas de Coinche" description="Applique le coefficient au score complet." checked={rules.scoring.doubleAllPointsOnCoinche} disabled={coincheDisabled} why="Activez d'abord la Coinche." onChange={(v) => toggle("scoring","doubleAllPointsOnCoinche",v)} /><Toggle label="Transférer les annonces en cas de chute" description="La défense récupère les annonces du preneur." checked={rules.scoring.announcementsLostOnFailure} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("scoring","announcementsLostOnFailure",v)} /><Toggle label="Transférer les annonces en cas de capot" description="Le camp du capot récupère les annonces." checked={rules.scoring.announcementsLostOnCapot} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("scoring","announcementsLostOnCapot",v)} /></section>
    <section aria-labelledby="rules-advanced" hidden={active !== "advanced"} className={sectionClass}><h3 className="font-bold" id="rules-advanced">Avancé</h3><label className="block p-2 font-semibold">Valeur de la Générale<input aria-label="Valeur de la Générale" className="ml-2 w-24 rounded border px-2 py-1" type="number" min={1} disabled={disabled || !rules.bidding.allowGenerale} value={rules.scoring.generaleBasePoints} onChange={(e) => update({ scoring: { generaleBasePoints: Number(e.target.value) } })} /></label>{!rules.bidding.allowGenerale ? <p className="px-2 text-xs text-stone-500">Activez d'abord la Générale.</p> : null}<Toggle label="Générale Sans Atout" description="Autorise explicitement ce mode pour la Générale." checked={rules.bidding.generaleAllowNoTrump} disabled={disabled || !rules.bidding.allowGenerale || !rules.bidding.allowNoTrump} why="Activez d'abord Générale et Sans Atout." onChange={(v) => toggle("bidding","generaleAllowNoTrump",v)} /><Toggle label="Générale Tout Atout" description="Autorise explicitement ce mode pour la Générale." checked={rules.bidding.generaleAllowAllTrump} disabled={disabled || !rules.bidding.allowGenerale || !rules.bidding.allowAllTrump} why="Activez d'abord Générale et Tout Atout." onChange={(v) => toggle("bidding","generaleAllowAllTrump",v)} />{[["coincheMultiplier","Multiplicateur Coinche"],["surcoincheMultiplier","Multiplicateur Surcoinche"]].map(([key,label]) => <label key={key} className="block p-2 font-semibold">{label}<input className="ml-2 w-20 rounded border px-2 py-1" type="number" min={1} disabled={coincheDisabled} value={rules.scoring[key as "coincheMultiplier"|"surcoincheMultiplier"]} onChange={(e) => update({ scoring: { [key]: Number(e.target.value) } })} /></label>)}</section>
  </div></div></div>;
}
