"use client";
/* eslint-disable react/no-unescaped-entities -- French dependency explanations use apostrophes. */

import React, { useState } from "react";

import { buildCustomRuleset, mergeRulesetDraft, rulesetToCustomInput, type CustomRulesetInput, type RulesetOverrides } from "@/engine/rulesets/custom";
import { CONTREE_KFFR_RULESET } from "@/engine/rulesets/presets";
import { RulesetSummary } from "./RulesetSummary";

const RULE_SECTIONS = [
  ["game", "Partie"], ["contracts", "Contrats"], ["announcements", "Annonces"], ["belote", "Belote"],
  ["card-play", "Jeu de la carte"], ["success", "Réussite du contrat"], ["score", "Score"], ["advanced", "Avancé"],
] as const;
type RuleSection = typeof RULE_SECTIONS[number][0];

type Props = { value: CustomRulesetInput; onChange: (value: CustomRulesetInput) => void; disabled?: boolean };

function Toggle({ label, description, checked, disabled, why, onChange }: { label: string; description: string; checked: boolean; disabled?: boolean; why?: string; onChange: (checked: boolean) => void }) {
  return <label className={`flex gap-3 rounded-md p-2 ${disabled ? "bg-stone-100 text-stone-400" : "hover:bg-stone-50"}`} title={disabled ? why : undefined}>
    <input className="mt-1 size-4 shrink-0" type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} />
    <span><span className="block font-semibold">{label}</span><span className="block text-xs opacity-75">{disabled && why ? why : description}</span></span>
  </label>;
}

export function RulesetConfigurator({ value, onChange, disabled = false }: Props) {
  const [active, setActive] = useState<RuleSection>("game");
  const [confirmReset, setConfirmReset] = useState(false);
  const rules = buildCustomRuleset(value);
  const update = (patch: RulesetOverrides) => onChange(mergeRulesetDraft(value, patch));
  const toggle = (section: keyof RulesetOverrides, key: string, checked: boolean) => update({ [section]: { [key]: checked } } as RulesetOverrides);
  const announcementsDisabled = disabled || !rules.announcements.enabled;
  const coincheDisabled = disabled || !rules.bidding.allowCoinche;
  const beloteDisabled = disabled || !rules.belote.enabled;
  const resetRules = () => { onChange(rulesetToCustomInput(CONTREE_KFFR_RULESET)); setConfirmReset(false); };
  return <div className="flex h-full min-h-0 flex-col text-sm">
    <div className="shrink-0 space-y-3 border-b bg-white/60 p-3 sm:p-4"><div className="grid gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs sm:grid-cols-2"><div><strong className="block text-amber-950">RÈGLES DE LA PARTIE</strong><span>Partagées, appliquées par le moteur et figées en partie multi.</span></div><div className="border-t border-amber-200 pt-2 sm:border-l sm:border-t-0 sm:pl-3 sm:pt-0"><strong className="block text-stone-700">MES PARAMÈTRES</strong><span>Restent personnels et ne changent pas dans ce configurateur.</span></div></div><div className="flex flex-wrap items-center gap-2"><label className="font-semibold">Variante <select className="ml-2 rounded-lg border px-2 py-1" disabled={disabled} value={rules.id === "contree-kffr" ? "contree-kffr" : "custom"} onChange={(event) => event.target.value === "contree-kffr" && (rules.id === "custom" ? setConfirmReset(true) : resetRules())}><option value="contree-kffr">Contrée KFFR</option><option value="custom">Personnalisée</option></select></label><span className={`rounded-full px-2 py-1 text-xs font-bold ${rules.id === "custom" ? "bg-amber-100 text-amber-900" : "bg-emerald-100 text-emerald-900"}`}>{rules.id === "custom" ? "Variante personnalisée" : "Preset officiel"}</span><button className="rounded-lg border border-red-300 bg-white px-2 py-1 font-semibold text-red-800 disabled:opacity-50" type="button" disabled={disabled} onClick={() => rules.id === "custom" ? setConfirmReset(true) : resetRules()}>Revenir à Contrée KFFR</button>{confirmReset ? <span className="flex items-center gap-1 rounded-lg bg-red-50 p-1"><span className="px-1 text-xs">Confirmer ?</span><button className="rounded bg-red-700 px-2 py-1 font-bold text-white" onClick={resetRules} type="button">Oui</button><button className="rounded border bg-white px-2 py-1" onClick={() => setConfirmReset(false)} type="button">Non</button></span> : null}</div><RulesetSummary ruleset={rules} compact showDifferences /></div>
    <div className="flex min-h-0 flex-1 flex-col md:grid md:grid-cols-[210px_minmax(0,1fr)]"><nav aria-label="Sections des règles" className="flex shrink-0 gap-1 overflow-x-auto border-b bg-stone-100 p-2 md:flex-col md:overflow-visible md:border-b-0 md:border-r md:p-4">{RULE_SECTIONS.map(([id,label]) => <button aria-current={active === id ? "page" : undefined} className={`whitespace-nowrap rounded-lg px-3 py-2 text-left font-semibold ${active === id ? "bg-amber-800 text-white" : "bg-white text-stone-700"}`} key={id} onClick={() => setActive(id)} type="button">{label}</button>)}</nav><div className="min-h-0 flex-1 overflow-y-auto p-3 sm:p-5">
    <section aria-labelledby="rules-game" hidden={active !== "game"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-game">Partie</h3><div className="mt-3 flex flex-wrap gap-2"><label className="font-semibold">Score cible<select className="ml-3 rounded border px-2 py-1" disabled={disabled} value={[500,1000,1500,2000].includes(rules.game.targetScore) ? rules.game.targetScore : "custom"} onChange={(e) => e.target.value !== "custom" && update({ game: { targetScore: Number(e.target.value) } })}>{[500,1000,1500,2000].map((score) => <option key={score}>{score}</option>)}<option value="custom">Personnalisé</option></select></label><input aria-label="Score cible personnalisé" className="w-28 rounded border px-2 py-1" disabled={disabled} min={100} max={100000} type="number" value={rules.game.targetScore} onChange={(e) => { const score = Number(e.target.value); if (score >= 100 && score <= 100000) update({ game: { targetScore: score } }); }} /></div></section>
    <section aria-labelledby="rules-contracts" hidden={active !== "contracts"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-contracts">Contrats</h3><div className="mt-2 grid gap-1 sm:grid-cols-2">
      <Toggle label="Capot" description="Permet d'annoncer les huit plis." checked={rules.bidding.allowCapot} disabled={disabled} onChange={(v) => toggle("bidding","allowCapot",v)} />
      <Toggle label="Générale" description="Un joueur s'engage à remporter seul les 8 plis. Son partenaire ne joue pas la donne." checked={rules.bidding.allowGenerale} disabled={disabled} onChange={(v) => toggle("bidding","allowGenerale",v)} />
      <Toggle label="Coinche" description="La défense peut contrer le contrat." checked={rules.bidding.allowCoinche} disabled={disabled} onChange={(v) => toggle("bidding","allowCoinche",v)} />
      <Toggle label="Surcoinche" description="Le camp preneur peut répondre à la Coinche." checked={rules.bidding.allowSurcoinche} disabled={coincheDisabled} why="Activez d'abord la Coinche." onChange={(v) => toggle("bidding","allowSurcoinche",v)} />
      <Toggle label="Sans Atout" description="Ordre et points hors-atout dans les quatre couleurs." checked={rules.bidding.allowNoTrump} disabled={disabled} onChange={(v) => toggle("bidding","allowNoTrump",v)} />
      <Toggle label="Tout Atout" description="Ordre et points d'atout dans les quatre couleurs." checked={rules.bidding.allowAllTrump} disabled={disabled} onChange={(v) => toggle("bidding","allowAllTrump",v)} />
    </div></section>
    <section aria-labelledby="rules-announcements" hidden={active !== "announcements"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-announcements">Annonces</h3><Toggle label="Jouer avec les annonces" description="Active les combinaisons annoncées." checked={rules.announcements.enabled} disabled={disabled} onChange={(v) => toggle("announcements","enabled",v)} /><div className="grid sm:grid-cols-2"><Toggle label="Tierce" description="3 cartes consécutives." checked={rules.announcements.tierce} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","tierce",v)} /><Toggle label="Cinquante" description="4 cartes consécutives." checked={rules.announcements.fifty} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","fifty",v)} /><Toggle label="Cent" description="5 cartes consécutives ou plus." checked={rules.announcements.hundred} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","hundred",v)} /><Toggle label="Carrés" description="4 cartes de même hauteur selon le barème." checked={rules.announcements.squares} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("announcements","squares",v)} /></div></section>
    <section aria-labelledby="rules-belote" hidden={active !== "belote"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-belote">Belote</h3><Toggle label="Belote / Rebelote" description="Roi et Dame d'atout." checked={rules.belote.enabled} disabled={disabled} onChange={(v) => toggle("belote","enabled",v)} /><label className="block p-2 font-semibold">Valeur <input className="ml-2 w-20 rounded border px-2 py-1" type="number" min={0} disabled={beloteDisabled} value={rules.belote.points} onChange={(e) => update({ belote: { points: Number(e.target.value) } })} /></label>{beloteDisabled ? <p className="px-2 text-xs text-stone-500">Activez d'abord la Belote / Rebelote.</p> : null}<Toggle label="Compte pour réussir le contrat" description="Ajoute la Belote aux points du preneur." checked={rules.belote.countsForContractSuccess} disabled={beloteDisabled} why="Activez d'abord la Belote." onChange={(v) => toggle("belote","countsForContractSuccess",v)} /><Toggle label="Compte pour faire chuter le contrat" description="Ajoute la Belote aux points de la défense." checked={rules.belote.countsForContractFailure} disabled={beloteDisabled} why="Activez d'abord la Belote." onChange={(v) => toggle("belote","countsForContractFailure",v)} /><Toggle label="Belote/Rebelote en Tout Atout" description="Chaque couleur peut produire une Belote." checked={rules.belote.allowInAllTrump} disabled={beloteDisabled || !rules.bidding.allowAllTrump} why="Activez d'abord Tout Atout et Belote / Rebelote." onChange={(v) => toggle("belote","allowInAllTrump",v)} /></section>
    <section aria-labelledby="rules-card-play" hidden={active !== "card-play"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-card-play">Jeu de la carte</h3>{[["mustFollowSuit","Obligation de fournir","Jouer la couleur demandée si possible."],["mustTrumpWhenVoid","Obligation de couper","Couper lorsqu'on n'a pas la couleur demandée."],["mustOvertrump","Obligation de surcouper","Monter sur l'atout adverse si possible."],["mustRaiseAtTrump","Obligation de monter à l'atout","Monter lorsque l'atout est demandé."],["allowDiscardWhenPartnerWinning","Défausse autorisée si le partenaire est maître","Permet de ne pas couper derrière son partenaire."],["allowDiscardWhenCannotOvertrump","Défausse autorisée si je ne peux pas surcouper","Permet de jeter une autre couleur."]] .map(([key,label,description]) => <Toggle key={key} label={label} description={description} checked={rules.cardPlay[key as keyof typeof rules.cardPlay]} disabled={disabled} onChange={(v) => toggle("cardPlay",key,v)} />)}</section>
    <section aria-labelledby="rules-success" hidden={active !== "success"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-success">Réussite du contrat</h3><Toggle label="Le preneur doit atteindre son contrat" description="Ses points doivent atteindre la valeur annoncée." checked={rules.contractSuccess.mustReachBid} disabled={disabled} onChange={(v) => toggle("contractSuccess","mustReachBid",v)} /><Toggle label="Le preneur doit battre la défense" description="Une égalité ne suffit pas." checked={rules.contractSuccess.mustBeatDefense} disabled={disabled} onChange={(v) => toggle("contractSuccess","mustBeatDefense",v)} /><Toggle label="Les annonces comptent pour réussir le contrat" description="Exemple : 88 aux plis + tierce = 108." checked={rules.contractSuccess.announcementsCount} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("contractSuccess","announcementsCount",v)} /></section>
    <section aria-labelledby="rules-score" hidden={active !== "score"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-score">Score</h3><label className="block p-2 font-semibold">Mode de score<select className="ml-2 rounded border px-2 py-1" disabled={disabled} value={rules.scoring.mode} onChange={(e) => update({ scoring: { mode: e.target.value as typeof rules.scoring.mode } })}><option value="ffb">FFB</option><option value="contract-only">Contrat uniquement</option><option value="contract-only-160-failure">Contrat uniquement / base de chute</option><option value="points-only">Points réalisés</option></select></label><Toggle label="Arrondir à la dizaine" description="Arrondi réglementaire en fin de manche." checked={rules.scoring.roundToTen} disabled={disabled} onChange={(v) => toggle("scoring","roundToTen",v)} /><Toggle label="Doubler tous les points en cas de Coinche" description="Applique le coefficient au score complet." checked={rules.scoring.doubleAllPointsOnCoinche} disabled={coincheDisabled} why="Activez d'abord la Coinche." onChange={(v) => toggle("scoring","doubleAllPointsOnCoinche",v)} /><Toggle label="Transférer les annonces en cas de chute" description="La défense récupère les annonces du preneur." checked={rules.scoring.announcementsLostOnFailure} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("scoring","announcementsLostOnFailure",v)} /><Toggle label="Transférer les annonces en cas de capot" description="Le camp du capot récupère les annonces." checked={rules.scoring.announcementsLostOnCapot} disabled={announcementsDisabled} why="Activez d'abord les annonces." onChange={(v) => toggle("scoring","announcementsLostOnCapot",v)} /></section>
    <section aria-labelledby="rules-advanced" hidden={active !== "advanced"} className="rounded-lg border bg-white p-3"><h3 className="font-bold" id="rules-advanced">Avancé</h3><label className="block p-2 font-semibold">Valeur de la Générale<input aria-label="Valeur de la Générale" className="ml-2 w-24 rounded border px-2 py-1" type="number" min={1} disabled={disabled || !rules.bidding.allowGenerale} value={rules.scoring.generaleBasePoints} onChange={(e) => update({ scoring: { generaleBasePoints: Number(e.target.value) } })} /></label>{!rules.bidding.allowGenerale ? <p className="px-2 text-xs text-stone-500">Activez d'abord la Générale.</p> : null}<Toggle label="Générale Sans Atout" description="Autorise explicitement ce mode pour la Générale." checked={rules.bidding.generaleAllowNoTrump} disabled={disabled || !rules.bidding.allowGenerale || !rules.bidding.allowNoTrump} why="Activez d'abord Générale et Sans Atout." onChange={(v) => toggle("bidding","generaleAllowNoTrump",v)} /><Toggle label="Générale Tout Atout" description="Autorise explicitement ce mode pour la Générale." checked={rules.bidding.generaleAllowAllTrump} disabled={disabled || !rules.bidding.allowGenerale || !rules.bidding.allowAllTrump} why="Activez d'abord Générale et Tout Atout." onChange={(v) => toggle("bidding","generaleAllowAllTrump",v)} />{[["coincheMultiplier","Multiplicateur Coinche"],["surcoincheMultiplier","Multiplicateur Surcoinche"]].map(([key,label]) => <label key={key} className="block p-2 font-semibold">{label}<input className="ml-2 w-20 rounded border px-2 py-1" type="number" min={1} disabled={coincheDisabled} value={rules.scoring[key as "coincheMultiplier"|"surcoincheMultiplier"]} onChange={(e) => update({ scoring: { [key]: Number(e.target.value) } })} /></label>)}</section>
  </div></div></div>;
}
