import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";

// Generated public artifact: reuse #118's exact CSS inputs/primitives and theme palette.
// It must load without Next bundles, application providers, images or network requests.
const globals = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
const viewport = globals.slice(globals.indexOf("/* Viewport and safe-area inputs."), globals.indexOf(".coinche-page-shell"));
const palette = globals.slice(globals.indexOf(":root,\n:root[data-theme"), globals.indexOf("\n* {"));
if (!viewport.includes("--safe-top") || !palette.includes("--app-bg")) throw new Error("Shared PWA CSS not found");
const html = `<!doctype html>
<!-- Generated by scripts/buildPwaOffline.mjs from the shared #118 CSS. -->
<html lang="fr" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"><meta name="theme-color" content="#071c17"><title>Connexion nécessaire | KFFR</title>
<script>(()=>{try{const p=JSON.parse(localStorage.getItem("coinche:player-preferences:v1")||"null");document.documentElement.dataset.theme=p?.visual?.theme==="light"?"light":"dark"}catch{}})()</script>
<style>${viewport}${palette}
*{box-sizing:border-box}html,body{margin:0;min-height:var(--viewport-dynamic);background:var(--app-bg);color:var(--text-primary);font-family:system-ui,sans-serif}
main{display:grid;align-items:center;overflow:auto}section{width:min(32rem,100%);margin:auto;padding:1.5rem}h1{font-size:1.8rem}p{color:var(--text-secondary);line-height:1.5}button{min-height:44px;margin-top:.5rem;border:1px solid var(--border-strong);border-radius:.75rem;padding:.75rem 1rem;background:var(--action-primary-bg);color:var(--action-primary-text);font:700 1rem system-ui;cursor:pointer}button:focus-visible{outline:3px solid var(--focus-ring);outline-offset:4px}
</style></head><body><main class="coinche-fullscreen-safe"><section><p>KFFR</p><h1>Connexion nécessaire</h1><p>KFFR a besoin d’une connexion Internet pour fonctionner.</p><button type="button" onclick="location.reload()">Réessayer</button></section></main></body></html>
`;
await writeFile(new URL("../public/pwa-offline.html", import.meta.url), html);
// A changed palette/offline screen must also change the worker bytes to trigger update.
const revision = createHash("sha256").update(html).digest("hex").slice(0, 16);
const workerPath = new URL("../public/sw.js", import.meta.url);
const worker = await readFile(workerPath, "utf8");
const versionedWorker = worker.replace(/const OFFLINE_CACHE = "kffr-offline-v1(?:-[a-f0-9]+)?";/, `const OFFLINE_CACHE = "kffr-offline-v1-${revision}";`);
if (!versionedWorker.includes(`kffr-offline-v1-${revision}`)) throw new Error("Offline worker cache marker not found");
await writeFile(workerPath, versionedWorker);
