import type { CosmeticsSnapshot } from "@/lib/profileCosmetics";
export function cosmeticsFixture(level = 1): CosmeticsSnapshot {
  return {
    catalogVersion: 1,
    equipped: { title: null, badge: null, frame: null },
    items: [
      {
        key: "title_taker",
        slot: "title",
        name: "Preneur",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 2,
      },
      {
        key: "title_steady_hand",
        slot: "title",
        name: "Main sûre",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 4,
      },
      {
        key: "title_strategist",
        slot: "title",
        name: "Stratège",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 6,
      },
      {
        key: "title_fearless",
        slot: "title",
        name: "Sans trembler",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 9,
      },
      {
        key: "title_auction_master",
        slot: "title",
        name: "Maître des enchères",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 12,
      },
      {
        key: "title_fine_blade",
        slot: "title",
        name: "Fine lame",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 16,
      },
      {
        key: "title_contree_ace",
        slot: "title",
        name: "As de la Contrée",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 20,
      },
      {
        key: "title_old_hand",
        slot: "title",
        name: "Vieux briscard",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 25,
      },
      {
        key: "title_table_master",
        slot: "title",
        name: "Maître de la table",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 32,
      },
      {
        key: "title_kffr_legend",
        slot: "title",
        name: "Légende KFFR",
        description: null,
        visualVariant: "standard",
        unlockType: "level",
        unlockLevel: 40,
      },
      {
        key: "badge_club",
        slot: "badge",
        name: "Trèfle",
        description: null,
        visualVariant: "club",
        unlockType: "level",
        unlockLevel: 3,
      },
      {
        key: "badge_diamond",
        slot: "badge",
        name: "Carreau",
        description: null,
        visualVariant: "diamond",
        unlockType: "level",
        unlockLevel: 5,
      },
      {
        key: "badge_spade",
        slot: "badge",
        name: "Pique",
        description: null,
        visualVariant: "spade",
        unlockType: "level",
        unlockLevel: 8,
      },
      {
        key: "badge_heart",
        slot: "badge",
        name: "Cœur",
        description: null,
        visualVariant: "heart",
        unlockType: "level",
        unlockLevel: 11,
      },
      {
        key: "badge_crown",
        slot: "badge",
        name: "Couronne",
        description: null,
        visualVariant: "crown",
        unlockType: "level",
        unlockLevel: 15,
      },
      {
        key: "badge_coinche",
        slot: "badge",
        name: "Coinche",
        description: null,
        visualVariant: "coinche",
        unlockType: "level",
        unlockLevel: 20,
      },
      {
        key: "badge_surcoinche",
        slot: "badge",
        name: "Surcoinche",
        description: null,
        visualVariant: "surcoinche",
        unlockType: "level",
        unlockLevel: 28,
      },
      {
        key: "badge_kffr",
        slot: "badge",
        name: "KFFR",
        description: null,
        visualVariant: "kffr",
        unlockType: "level",
        unlockLevel: 40,
      },
      {
        key: "frame_gold_fine",
        slot: "frame",
        name: "Or fin",
        description: null,
        visualVariant: "gold_fine",
        unlockType: "level",
        unlockLevel: 5,
      },
      {
        key: "frame_ivory",
        slot: "frame",
        name: "Ivoire",
        description: null,
        visualVariant: "ivory",
        unlockType: "level",
        unlockLevel: 10,
      },
      {
        key: "frame_black_gold",
        slot: "frame",
        name: "Noir & Or",
        description: null,
        visualVariant: "black_gold",
        unlockType: "level",
        unlockLevel: 15,
      },
      {
        key: "frame_contree",
        slot: "frame",
        name: "Contrée",
        description: null,
        visualVariant: "contree",
        unlockType: "level",
        unlockLevel: 22,
      },
      {
        key: "frame_prestige",
        slot: "frame",
        name: "Prestige",
        description: null,
        visualVariant: "prestige",
        unlockType: "level",
        unlockLevel: 30,
      },
      {
        key: "frame_kffr_signature",
        slot: "frame",
        name: "KFFR Signature",
        description: null,
        visualVariant: "kffr_signature",
        unlockType: "level",
        unlockLevel: 40,
      },
    ]
      .filter((item) => level >= item.unlockLevel)
      .map((item) => ({
        ...item,
        unlocked: level >= item.unlockLevel,
        unlockedAt: level >= item.unlockLevel ? "2026-10-01T00:00:00Z" : null,
        equipped: false,
      })),
  } as CosmeticsSnapshot;
}
export function withEquipment(level = 40, slots = ["title", "badge", "frame"]) {
  const snapshot = cosmeticsFixture(level);
  for (const slot of slots) {
    const item = snapshot.items.find((i) => i.slot === slot && i.unlocked)!;
    item.equipped = true;
    snapshot.equipped[item.slot] = item.key;
  }
  return snapshot;
}
